api:
  host: "0.0.0.0"
  port: "8081"
  base: /api
  tls:
    port: "8082"

tls:
  store: mule.jks
  pass: changeit
  crt:
    name: server-crt
    pass: password

claims-proc:
  protocol: HTTPS
  host: claims-proc-ssin.us-e2.cloudhub.io
  port: "443"
  base: /api