api:
    application_name: "demo-api"
    auto_discovery_id: "12345678"
    version: "v1"
    buildVersion: "local.feature.1234"

local:
    host: "localhost"
    port: "8081"
    basepath: "demo-api"
    tls-port: "8082"
    tls-keystore: "/tmp/keystore/jks/mule.jks"
    tls-keystore-password: "![secure::$MULE_TLS_KEYSTORE_SECRET]"
    tls-server-cert: "$MULE_SERVER_CERT_ALIAS"
    tls-sever-cert-password: "![secure::$MULE_ALIAS_SERVER_CERT_SECRET]"
    tls-trust-keystore: "/tmp/keystore/jks//mule-trust.jks"
    tls-trust-keystore-password: "![secure::$MULE_TLS_KEYSTORE_SECRET]"
