api:
  host: "127.0.0.1"
  port: "8083"
  base: /api
  tls:
    port: "8084"

tls:
  store: mule.jks
  pass: changeit
  crt:
    name: server-crt
    pass: password

claims-sys:
  protocol: HTTP
  # Change hostname when you deploy to cloudhub
  host: "127.0.0.1"
  port: "8085"
  base: /api